---
routes:

    #########################################################
    # ADM / NODES                                           #
    #########################################################

    fe_adm:
        service:    adm
        path:       /adm
        pattern:    /adm
        label:      Adm
        dscr:       A routegroup, no methods here.

    #########################################################
    # ADM / PHPINFO                                         #
    #########################################################

    fe_adm_phpinfo:
        pattern:    ${routes.fe_adm.path}/phpinfo
        path:       ${routes.fe_adm.path}/phpinfo
        label:      Phpinfo()
        dscr:       ~
        service:    adm
        methods:
            get:    ~

    fe_adm_adminer:
        pattern:    ${routes.fe_adm.path}/adminer
        path:       ${routes.fe_adm.path}/adminer
        label:      Adminer
        dscr:       ~
        service:    adm
        methods:
            get:    ~
            post:   ~

    #########################################################
    # ADM / NODES                                           #
    #########################################################

    be_adm:
        service:    adm
        path:       /api/adm
        pattern:    /api/adm
        label:      Adm
        dscr:       A routegroup, no methods here.

    #########################################################
    # ADM / HEALTH                                          #
    #########################################################

    be_adm_health_v1:
        pattern:    ${routes.be_adm.path}/health/v1
        path:       ${routes.be_adm.path}/health/v1
        label:      Adm health
        dscr:       A healthcheck endpoint for the microservice.
        service:    adm
        provides:   health
        methods:
            get:    ~

    be_adm_network_arp_v1:
        pattern:    ${routes.be_adm.path}/network/arp/v1
        path:       ${routes.be_adm.path}/network/arp/v1
        label:      Arp-scan
        dscr:       Get all devices on network.
        service:    adm
        methods:
            get:    ~

    be_adm_network_map_v1:
        pattern:    ${routes.be_adm.path}/network/map/v1
        path:       ${routes.be_adm.path}/network/map/v1
        label:      Nmap
        dscr:       Probe most common ports on network devices.
        service:    adm
        methods:
            get:    ~
